### ISSUE TITLE
Use async fs calls?

### ISSUE THREAD

**Issue by mifi** [nebrius/raspi-led#3]
Hi
Whould it be better to use async methods instead of existsSync, writeFileSync, readFileSync?
If the OS calls block it will also block all other JS code, including maybe time critical things.

**Comment by nebrius** [comment]
I use the synchronous methods because upstream consumers of raspi-led require a synchronous API interface. This isn't to say that I can't make it work with the asynchronous methods under the hood, but it's complicated and bug-prone to implement.

Since we're on a device writing client code, not on a server handling a bunch of requests simultaneously, this isn't _likely_ to be nearly as much of an issue. Timing critical stuff shouldn't be run in any garbage collected language on an OS with threads, because you can get delays of many milliseconds just from that.

That said, there may be some use cases I'm not aware of where this matters. Are you running into issues because of this design decision?

**Comment by mifi** [comment]
Sorry I was a bit quick, I thought it was a standalone module for controlling the onboard leds. I see that this package is part of a bigger system. Makes sense that you don't want to change the signatures. I wasn't thinking about callbacks btw, but using promises (async / await) which are simple to implement, but will of course change the signature also.
I'm developing a somewhat time critical system now, and that's why I was checking the source code to see how it was doing the FS-calls. But I'll close this as a misunderstanding.

**Comment by nebrius** [comment]
Best of luck @mifi! And if you're doing time critical stuff, I'd recommend using Rust or C++ instead of Node.js or Python (seriously, GC and thread preemption will hurt performance more than synchronous filesystem calls). Or better yet, offload the timing critical stuff to a OS-less device like an Arduino or ESP8266.

**Comment by mifi** [comment]
Thanks! Yeah I know. but for a POC, I think Node.js will do just fine, with averaging. By somewhat critical i mean <100ms. Arduino is of course optimal but way more time consuming to implement than node.js. raspberry pi is just so convenient and easy to make anything :)
